# Generated by Django 3.0.5 on 2020-04-24 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='plates',
            field=models.CharField(max_length=8),
        ),
    ]
